### ISSUE TITLE
Test: Tableplot

### ISSUE THREAD

**Issue by VivyanCyril** [VivyanCyril/SCELSE-NUS-Internship-2017#3]
I assigned 6 random Phyla to the Taxa (not according, just to test out the plot...) and formated the data...

Stacked Barplot
-----------------------------------------------------------
I can get a horizontal stacked barplot by using barplot(), making one bar = one sample.
(Total: 60 samples => 60 bars)

The data looks something like this:

Phylum \ Sample
--------------------------------- S.1 ------------- S.2 -------------- S.3 -------------- S.4 ........ S.60
Proteobacteria ---------------- 0.2 -------------- 0.1 ...
Cyanobacteria -----------------0.2 -------------- 0.2 ...
Actinobacteria -----------------0.1 -------------- 0.2 ...
Bacteroidetes ------------------0.0 -------------- 0.3 ...
Firmicutes-----------------------0.4 -------------- 0.0 ...
Chlamydiae---------------------0.1 -------------- 0.2 ...

 which gives this plot:

![stacked barplot test](https://user-images.githubusercontent.com/30431396/29558356-68b49d08-875e-11e7-8496-9ade66b98f9c.jpeg)

Tabplot \  Phylum and Land.use
--------------------------------------------------------------------------

To get a tableplot, I format the data again, now it looks something like this:

**Phylum------------------- Rel.Abundance --------------Sample -----------------Land.Use**
Proteobacteria ---------------- 0.0002 ------------------------ S1--------------------Industrial
Proteobacteria -----------------0.0012 ------------------------ S2--------------------Industrial
Proteobacteria -----------------0.0001 -------------- --------- S4--------------------Industrial
Proteobacteria -----------------0.0000 ----------------------- S1-------------------- Residential
Proteobacteria----------------- 0.0041 -------------- --------- S1--------------------Residential
Proteobacteria------------------0.0013 -------------- --------- S1--------------------Industrial

.......... and so on, returning 63.442 rows in total, after removing zero counts.

Which gives this plot:

![tableplot_test_phylum_landuse](https://user-images.githubusercontent.com/30431396/29559156-dacfb38a-8760-11e7-9f59-639fc286a54a.jpeg)

Problem:
------------------------------------------------------
Tableplot can not give me samples as rows here.

It treats each individual taxa as one object = one row and then specifies, which Phylum it belongs to, and which is the respective Land.use.

**Comment by adityabandla** [comment]
Hi Lena

If indeed it treats each taxa as one row, it doesnt make sense that each taxa could belong to multiple phyla? Im still trying to understand whats going on in the above plot

Cheers,
Aditya

**Comment by VivyanCyril** [comment]
Hi Aditya,

It only looks like each taxa has multiple Phyla, because there are multiple objects displayed in one row. 

Cheers,
Lena


Von meinem iPhone gesendet

**Comment by adityabandla** [comment]
Hi Lena

Something to think about. If tableplot indeed only plot categorical variables as a stacked barplot, then we dont need to have the relative abundance values of the taxa as a number at all. Just the names of the taxa per sample has this info implicitly

makes sense?

Cheers,
Aditya

**Comment by VivyanCyril** [comment]
If we set sort = Land.use the plot looks like this...

![tableplot_test_sort_landuse](https://user-images.githubusercontent.com/30431396/29564061-cdf49f06-8772-11e7-94bd-2c52eb11aae6.jpeg)

**Comment by adityabandla** [comment]
How about sort by sample?

**Comment by VivyanCyril** [comment]
I think it gives a similar result as sort by Landuse:

![tableplot_test_sample](https://user-images.githubusercontent.com/30431396/29564296-ba961178-8773-11e7-9fb3-e7c52417912b.jpeg)

**Comment by adityabandla** [comment]
I think this makes sense. Your thought?

**Comment by VivyanCyril** [comment]
Considering that the Phyla are just imagined, it might actually make sense with real data, yes.
