### ISSUE TITLE
A preprocessing problem

### ISSUE THREAD

**Issue by VivyanCyril** [VivyanCyril/SCELSE-NUS-Internship-2017#6]
I want to filter the OTU table and remove taxa that are **not seen more than 3 times in at least 20% of the samples**. However this removes a ridiculously huge amount of taxa:

```
tsf <- filter_taxa(sample.taxa.sediment, function(x) sum(x > 3) > (0.2*length(x)), TRUE)
# Remove taxa not seen more than 3 times in at least 20% of samples
ntaxa(tsf) # only 421 of originally 8357 taxa are kept
```

I tried changing the function so that less taxa would be removed, by changing the threshhod to at least 50% of the samples. However now even MORE taxa are removed. Why?

```
tsf <- filter_taxa(sample.taxa.sediment, function(x) sum(x > 3) > (0.5*length(x)), TRUE)
# Remove taxa not seen more than 3 times in at least 50% of samples
ntaxa(tsf) # only 122 of originally 8357 taxa are kept
```

I am not sure where is the mistake in my thinking.

**Comment by adityabandla** [comment]
Seems like you are removing taxa that have counts >3. I think your original intention was to remove taxa with counts less than 3 (<3), but your code suggests the opposite (>3)

Also, one will expect less taxa to be shared across samples. So more taxa will be retained at less overlap values (i.e. more taxa at 20% than 50%)

**Comment by VivyanCyril** [comment]
Ok, now I understand, thanks much! I probably mixed it up with the genefilter_sample() function, which gives a criteria for OTUs to be kept, while filter_taxa() gives a criteria for OTUs to be removed. (Then, I guess this mistake is also in the phyloseq tutorial: https://joey711.github.io/phyloseq/preprocess.html )
